spring:
    datasource:
        username: root
        password: Pei1234+-
        url: jdbc:mysql://localhost:3306/db-movies       
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    servlet:
        multipart:    
            max-file-size: 10MB        
            max-request-size: 10MB    
    mail:
        host: smtp.gmail.com 
        port: 587
        username: "example@gmail.com"           
        password: "code"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true


project:
    poster: api-movie/posters/  

base:
    url: "http://localhost:8080"                  